"""add product merchant fields

Revision ID: 164e48411da8
Revises: d25f009e99c8
Create Date: 2026-09-12 20:30:00.805082
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = '164e48411da8'
down_revision: Union[str, None] = 'd25f009e99c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('merchant_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('merchant_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'merchant_id')
    op.drop_column('products', 'merchant_name')
    # ### end Alembic commands ###
