"""add password reset tokens and affiliate networks

Revision ID: 94aa20be6186
Revises: 272686750482
Create Date: 2026-09-11 17:44:29.000765
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = '94aa20be6186'
down_revision: Union[str, None] = '272686750482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_networks',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_networks_id'), 'affiliate_networks', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_networks_slug'), 'affiliate_networks', ['slug'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # batch mode: SQLite can't ALTER a constraint in place (needs the
    # copy-and-move strategy); batch mode also works fine on Postgres.
    with op.batch_alter_table('retailers') as batch_op:
        batch_op.add_column(sa.Column('affiliate_network_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_retailers_affiliate_network_id', 'affiliate_networks', ['affiliate_network_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailers') as batch_op:
        batch_op.drop_constraint('fk_retailers_affiliate_network_id', type_='foreignkey')
        batch_op.drop_column('affiliate_network_id')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_affiliate_networks_slug'), table_name='affiliate_networks')
    op.drop_index(op.f('ix_affiliate_networks_id'), table_name='affiliate_networks')
    op.drop_table('affiliate_networks')
    # ### end Alembic commands ###
