"""add outfit compatibility score and notes

Revision ID: bf592b00b6dd
Revises: c3726455a184
Create Date: 2026-09-11 23:07:28.453539
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = 'bf592b00b6dd'
down_revision: Union[str, None] = 'c3726455a184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('compatibility_score', sa.Integer(), nullable=True))
    op.add_column('outfits', sa.Column('compatibility_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'compatibility_notes')
    op.drop_column('outfits', 'compatibility_score')
    # ### end Alembic commands ###
